var programmingViewmodel = {
    workoutTypes: [
        {WorkoutType: "AMRAP"},
        {WorkoutType: "Chipper"},
        {WorkoutType: "Rounds for time"},
        {WorkoutType: "Tabata"},
        {WorkoutType: "Technique"},
        { WorkoutType: "Strength" }
    ]
}

var standingsViewModel = {
    classes: [
        {className: "Individual Pro", val: "#indPro"},
        {className: "Individual Open", val: "#indOpen"},
        {className: "Team Pro", val: "#teamPro"},
        {className: "Team Open", val: "#teamOpen"}
    ],
    individualPro: [
        { id: 1, fullName: "Ind Pro 1", points: "100" },
        { id: 2, fullName: "Ind Pro 2", points: "98" },
        { id: 3, fullName: "Ind Pro 3", points: "95" },
        { id: 4, fullName: "Ind Pro 4", points: "92" },
        { id: 5, fullName: "Ind Pro 5", points: "89" },
        { id: 6, fullName: "Ind Pro 6", points: "85" },
        { id: 7, fullName: "Ind Pro 7", points: "75" },
        { id: 8, fullName: "Ind Pro 8", points: "64" },
        { id: 9, fullName: "Ind Pro 9", points: "62" },
        { id: 10, fullName: "Ind Pro 10", points: "59" },
        { id: 11, fullName: "Ind Pro 11", points: "52" },
        { id: 12, fullName: "Ind Pro 12", points: "49" },
        { id: 13, fullName: "Ind Pro 13", points: "46" },
        { id: 14, fullName: "Ind Pro 14", points: "43" },
        { id: 15, fullName: "Ind Pro 15", points: "38" },
        { id: 16, fullName: "Ind Pro 16", points: "35" },
        { id: 17, fullName: "Ind Pro 17", points: "25" },
        { id: 18, fullName: "Ind Pro 18", points: "22" },
        { id: 19, fullName: "Ind Pro 19", points: "15" },
        { id: 20, fullName: "Ind Pro 20", points: "0" },
    ],
    individualOpen: [
        { id: 1, fullName: "Ind Open 1", points: "100" },
        { id: 2, fullName: "Ind Open 2", points: "98" },
        { id: 3, fullName: "Ind Open 3", points: "95" },
        { id: 4, fullName: "Ind Open 4", points: "92" },
        { id: 5, fullName: "Ind Open 5", points: "89" },
        { id: 6, fullName: "Ind Open 6", points: "85" },
        { id: 7, fullName: "Ind Open 7", points: "75" },
        { id: 8, fullName: "Ind Open 8", points: "64" },
        { id: 9, fullName: "Ind Open 9", points: "62" },
        { id: 10, fullName: "Ind Open 10", points: "59" },
        { id: 11, fullName: "Ind Open 11", points: "52" },
        { id: 12, fullName: "Ind Open 12", points: "49" },
        { id: 13, fullName: "Ind Open 13", points: "46" },
        { id: 14, fullName: "Ind Open 14", points: "43" },
        { id: 15, fullName: "Ind Open 15", points: "38" },
        { id: 16, fullName: "Ind Open 16", points: "35" },
        { id: 17, fullName: "Ind Open 17", points: "25" },
        { id: 18, fullName: "Ind Open 18", points: "22" },
        { id: 19, fullName: "Ind Open 19", points: "15" },
        { id: 20, fullName: "Ind Open 20", points: "0" },
    ],
    teamPro: [
        { id: 1, fullName: "Team Pro 1", points: "100" },
        { id: 2, fullName: "Team Pro 2", points: "98" },
        { id: 3, fullName: "Team Pro 3", points: "95" },
        { id: 4, fullName: "Team Pro 4", points: "92" },
        { id: 5, fullName: "Team Pro 5", points: "89" },
        { id: 6, fullName: "Team Pro 6", points: "85" },
        { id: 7, fullName: "Team Pro 7", points: "75" },
        { id: 8, fullName: "Team Pro 8", points: "64" },
        { id: 9, fullName: "Team Pro 9", points: "62" },
        { id: 10, fullName: "Team Pro 10", points: "59" },
        { id: 11, fullName: "Team Pro 11", points: "52" },
        { id: 12, fullName: "Team Pro 12", points: "49" },
        { id: 13, fullName: "Team Pro 13", points: "46" },
        { id: 14, fullName: "Team Pro 14", points: "43" },
        { id: 15, fullName: "Team Pro 15", points: "38" },
        { id: 16, fullName: "Team Pro 16", points: "35" },
        { id: 17, fullName: "Team Pro 17", points: "25" },
        { id: 18, fullName: "Team Pro 18", points: "22" },
        { id: 19, fullName: "Team Pro 19", points: "15" },
        { id: 20, fullName: "Team Pro 20", points: "0" },
    ],
    teamOpen: [
        { id: 1, fullName: "Team Open 1", points: "100" },
        { id: 2, fullName: "Team Open 2", points: "98" },
        { id: 3, fullName: "Team Open 3", points: "95" },
        { id: 4, fullName: "Team Open 4", points: "92" },
        { id: 5, fullName: "Team Open 5", points: "89" },
        { id: 6, fullName: "Team Open 6", points: "85" },
        { id: 7, fullName: "Team Open 7", points: "75" },
        { id: 8, fullName: "Team Open 8", points: "64" },
        { id: 9, fullName: "Team Open 9", points: "62" },
        { id: 10, fullName: "Team Open 10", points: "59" },
        { id: 11, fullName: "Team Open 11", points: "52" },
        { id: 12, fullName: "Team Open 12", points: "49" },
        { id: 13, fullName: "Team Open 13", points: "46" },
        { id: 14, fullName: "Team Open 14", points: "43" },
        { id: 15, fullName: "Team Open 15", points: "38" },
        { id: 16, fullName: "Team Open 16", points: "35" },
        { id: 17, fullName: "Team Open 17", points: "25" },
        { id: 18, fullName: "Team Open 18", points: "22" },
        { id: 19, fullName: "Team Open 19", points: "15" },
        { id: 20, fullName: "Team Open 20", points: "0" },
    ],
}